import turtle
screen=turtle.Screen()
pen=turtle.Turtle()
pen.fillcolor('grey')
pen.begin_fill()
pen.forward(200)
pen.left(90)
pen.forward(200)
pen.left(90)
pen.forward(200)
pen.left(90)
pen.forward(200)
pen.left(90)
pen.end_fill()
screen.exitonclick()
