import turtle
screen=turtle.Screen()
screen.bgcolor("grey")
screen.title("my first drawing")
pen=turtle.Turtle()
pen.shape('turtle')
pen.color('purple')
pen.fillcolor('cyan')
pen.forward(200)
pen.left(90)
pen.forward(200)
pen.right(30)
pen.backward(380)
pen.left(30)
pen.forward(130)
turtle.done()
pen.up()
pen.goto(50,50)